### ISSUE TITLE
How to get themes from another repository other than this one and how to obtain wallpapers as local files?

### ISSUE THREAD

**Issue by YuvanMichaelVivenzi** [HyDE-Project/hyde-gallery#27]
Wiki is outdated and cannot figure out how to get a new theme from somewhere other than hyde-gallery. Also, cannot find wallpapers in github repositories of these themes, How do I get them as local files?

**Comment by kRHYME7** [comment]
> How to get themes from another repository other than this 

Discord

**Comment by kRHYME7** [comment]
> how to obtain wallpapers as local files?


wallpapers from themes are located at ~/.config/hyde/themes/wallpapers

**Comment by kRHYME7** [comment]
Also we have 30 themes in here, you need more

**Comment by YuvanMichaelVivenzi** [comment]
Just in case I find some, you know there are pull requests in here to add other themes, In case I want them I would like to install that's why.

**Comment by YuvanMichaelVivenzi** [comment]
Is there any straight one line command to install any HyDE theme from any repository?

**Comment by kRHYME7** [comment]
yup 

` Hyde theme import 'Theme Name' 'http://github.com/owner/theme-name'

**Comment by kRHYME7** [comment]
> Just in case I find some, you know there are pull requests in here to add other themes, In case I want them I would like to install that's why.

This repo only have the metadata and the preview images of the theme. The themes are still on there respective  repo 

Click each of these boxes to check there repo 
![image](https://github.com/user-attachments/assets/2c710f88-3e16-42ab-aae1-c6a557c9225e)

**Comment by kRHYME7** [comment]
When you visit, there will be instructions to install the theme individually 

![image](https://github.com/user-attachments/assets/b185b1ac-6833-4f9d-b6b5-d733bf5393fd)

**Comment by YuvanMichaelVivenzi** [comment]
Thanks!
