### ISSUE TITLE
bug:  themes are not downloading

### ISSUE THREAD

**Issue by Neil-Tomar** [HyDE-Project/hyde-gallery#36]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

v0.6.0-4-ga809d66

### Operating system/version

Arch

### Describe the bug

the themes are not installing on their directory

Hyde theme import
[themepatcher] Patching 30 theme/s...
====================================================================================================================================================================================
Mac OS
Windows 11
Hack the Box
One Dark
Dracula
Catppuccin Latte
Catppuccin Mocha
Decay Green
Edge Runner
Frosted Glass
Graphite Mono
Gruvbox Retro
Material Sakura
Nordic Blue
Sci-fi
Synth Wave
Tokyo Night
Rosé Pine
AbyssGreen
Abyssal-Wave
Red Stone
Rain Dark
Paranoid Sweet
Solarized Dark
Green Lush
Greenify
Monokai
Scarlet Night
Oxo Carbon
Ice Age
====================================================================================================================================================================================
[ENTER] continue [ANY]  Exit:
53% 16:14=3m13s Abyssal-Wave https://github.com/Itz-Abhishek-Tiwari/Abyssal-Wave --skipcaching false                                                                                  Select a Branch

1) Abyssalhorizon
2) main
100% 30:0=11m05s Ice Age https://github.com/saber-88/Ice-Age --skipcaching false                                                                                                      

[cache] generating cache files...
100% 51:0=0s 7cd12a23084b0ad1e02b9053f9322afbd35cfb10 /home/Neil/.config/hyde/themes/Tokyo Night/wallpapers/tokyo_pink.png                                                            
[OK] Mac OS
[OK] Windows 11
[OK] Hack the Box
[OK] One Dark
[OK] Dracula
[OK] Catppuccin Latte
[OK] Catppuccin Mocha
[OK] Decay Green
[OK] Edge Runner
[OK] Frosted Glass
[OK] Graphite Mono
[OK] Gruvbox Retro
[OK] Material Sakura
[OK] Nordic Blue
[OK] Sci-fi
[OK] Synth Wave
[OK] Tokyo Night
[OK] Rosé Pine
[OK] AbyssGreen
[OK] Abyssal-Wave
[OK] Red Stone
[OK] Rain Dark
[OK] Paranoid Sweet
[OK] Solarized Dark
[OK] Green Lush
[OK] Greenify
[OK] Monokai
[OK] Scarlet Night
[OK] Oxo Carbon
[OK] Ice Age
 11m12s ••     
•   Hyde theme set
WARNING: No image found in "/home/Neil/.config/hyde/themes/Oxo Carbon"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Hack the Box"
WARNING: No image found in "/home/Neil/.config/hyde/themes/One Dark"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Dracula"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Mac OS"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Greenify"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Sci-fi"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Graphite Mono"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Ice Age"
WARNING: No image found in "/home/Neil/.config/hyde/themes/AbyssGreen"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Rosé Pine"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Abyssal-Wave"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Solarized Dark"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Windows 11"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Paranoid Sweet"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Monokai"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Scarlet Night"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Catppuccin Latte"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Catppuccin Mocha"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Rain Dark"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Red Stone"
WARNING: No image found in "/home/Neil/.config/hyde/themes/Green Lush"
:: applying theme :: "Gruvbox Retro"
:: applying wall :: "/home/Neil/.config/hyde/themes/Gruvbox Retro/wallpapers/finalizer.png"
 51s ••     
 51s ••     
[skip: no dir] "/home/Neil/.config/spicetify/Themes/Sleek/color.ini"

### Steps To Reproduce

1.Hyde theme import
2.Hyde theme set

### Expected Behavior

the theme should be installed in .config/hyde/themes/Green Lush but they are not there all the folders are empty

**Comment by kRHYME7** [comment]
How about installing lesser themes one at a time? maybe 2 or 3?

**Comment by Jigarvarma2005** [comment]
Re-running the `Hyde theme import` command effectively resolves this issue, although it’s important to note that this is only a temporary solution and not a permanent fix.

**Comment by kRHYME7** [comment]
> edit: yes once while i installed arch then i tried installing 1 theme at a time and then i managed to get 5-6 themes in total and then it again failed to install more themes


What errors you got.  Just reply on your free time, exams are more important.

**Comment by Neil-Tomar** [comment]
it still didn't work

**Comment by kRHYME7** [comment]
what command did you run?

**Comment by Neil-Tomar** [comment]
first i run 
yay -Sy hyde-cli-git

and then 

Hyde theme import

**Comment by kRHYME7** [comment]
even tried searching that error? or even the arch wiki?

You can remove that file. ` /var/lib/pacman/db.lck` if you're sure that there's no ongoing updates somewhere.

**Comment by Neil-Tomar** [comment]
yes i fixed that and everything is perfect right now but themes are still not working it just download them and then it just vanish i don't know whats happening but at this point i am like i am good without those themes it doesn't matter anymore
