### ISSUE TITLE
bug: some themes display errors and can't be installed

### ISSUE THREAD

**Issue by Ramy-Ashraf** [HyDE-Project/hyde-gallery#41]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

v0.1.0.r303.5a0423a

### Operating system/version

Arch linux

### Describe the bug

![image](https://github.com/user-attachments/assets/31e09216-2745-434a-846f-6d5be82a2580)
as shown in the picture, theme, icon and cursor can't be found

### Steps To Reproduce

1. Hyde theme import
2. select a new theme to install
3. errors happen as showed

### Expected Behavior

theme to be installed

**Comment by kRHYME7** [comment]
update the cli `yay - Sy hyde-cli-git`

**Comment by Ramy-Ashraf** [comment]
thank you very much.
it worked.
