### ISSUE TITLE
bug: skipcaching

### ISSUE THREAD

**Issue by Abderrahmane-jacker** [HyDE-Project/hyde-gallery#57]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

0.1.0

### Operating system/version

Arch

### Describe the bug

when i write "Hyde theme import " i get a lot of --skipcaching false is it normal or i need to update Hyde-cli

### Steps To Reproduce

1.Hyde theme import

### Expected Behavior

--skipcaching false

**Comment by kRHYME7** [comment]
It's normal
