### ISSUE TITLE
bug: Unable to Import Themes from Missing User Account 

### ISSUE THREAD

**Issue by Soumik0906** [HyDE-Project/hyde-gallery#58]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

v0.6.0-25-g076245a

### Operating system/version

Arch Linux x86_64

### Describe the bug

Hello,

I am encountering an issue while importing themes using hyde-cli. It appears that themes previously contributed by the user rishav12s are no longer accessible, as their GitHub account seems to have been deleted. I verified this by visiting their profile, which is no longer active.

This results in an error when attempting to import themes associated with their account. Could you kindly update the theme sources or remove any references to rishav12s to resolve this issue?

### Steps To Reproduce

1. Run hyde-cli (Hyde theme import) and attempt to import a theme contributed by rishav12s (eg:- Eternal Arctic)
2. Encounter an error while importing theme. 

### Expected Behavior

Themes should be imported without issues, even if the user account is no longer active. If possible, alternative theme sources should be added.

Thank you for your attention to this matter!

**Comment by kRHYME7** [comment]
@Soumik0906  which theme?

**Comment by Soumik0906** [comment]
> @Soumik0906 which theme?

Eternal Arctic, Vanta Black and a few others

**Comment by kRHYME7** [comment]
I see, 

> Themes should be imported without issues, even if the user account is no longer active. If possible, alternative theme sources should be added.


We can't control that. github had the repository. unless we have another mirror for the files. 

Dunno what happened but he's alive and kicking few hours ago,

**Comment by kRHYME7** [comment]
The DB can't keep track (yet) the availability of the links, maybe we can do a github workflow for that. But I don't have much idea how to do it lols. 
My idea is to have a schedule to check the links if they're alive.  
then remove deadlinks in the DB

**Comment by kRHYME7** [comment]
> Is there any other way I can use those themes, since they are mentioned in the list of import themes?

Wait for him. I think his acount is breached or something is wrong with GH.
